config/routes.rb
Recordlabel::Application.routes.draw do

  resources :releases do
    member do
      get :confirm_destroy
    end
  end
  
  resources :artists
  
  root :to => 'releases#index'
end

app/models/artist.rb
class Artist < ActiveRecord::Base
  has_many :releases, :dependent => :delete_all
end

app/models/release.rb
class Release < ActiveRecord::Base
  belongs_to :artist
  
  def artist_name
    artist.name if artist
  end
  
  def artist_name=(name)
    self.artist = Artist.find_or_create_by_name(name) unless name.blank?
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController

def show
  @artist = Artist.find params[:id]
end

def edit
  @artist = Artist.find params[:id]
end

def update
  @artist = Artist.find params[:id]
  
  if (@artist.update_attributes(params[:artist]))
    flash[:notice] = "#{@artist.name} saved."
    redirect_to artist_path(@artist)
  end
end

end

app/controllers/releases_controller.rb
class ReleasesController < ApplicationController
  def index
    @releases = Release.order("created_at desc")
  end
  
  def show
    @release = Release.find params[:id]
  end
  
  def new
    @title = "New Release"
    @release = Release.new
  end
  
  def create
    @release = Release.new(params[:release])
    
    if @release.save
      respond_to do |format|
        format.html {redirect_to releases_path}
      end
    end
  end
  
  def edit
    @title = "Edit Release"
    @release = Release.find params[:id]
  end
  
  def update
    @release = Release.find params[:id]
    
    if (@release.update_attributes(params[:release]))
      flash[:notice] = "#{@release.title} saved."
      redirect_to releases_path
    end
  end
  
  def destroy
    @release = Release.find params[:id]
    @release.destroy
    
    respond_to do |format|
      format.html {
        flash[:notice] = "Release deleted"
        redirect_to releases_path
      }
      format.js {
        @release_count = Release.all.count
        @no_releases = render_to_string "_no_releases"  
      }
    end
  end
  
  def confirm_destroy
    @title = "Confirm Delete Release"
    @release = Release.find params[:id]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/releases_helper.rb
module ReleasesHelper
  def link_to_destroy(name, url, fallback_url, authenticity_token, id)
    link_to_function name, "confirm_destroy(this,'#{url}','#{authenticity_token}')", :href => fallback_url, :class => "delete", :id => id
  end
  
  def one_line(&block)
    haml_concat capture_haml(&block).gsub("\n", '').gsub('\\n', "\n")
  end
end

app/views/artists/edit.html.erb
<%= form_for @artist do |f| %>
	<fieldset>
		<ol>
			<li>
				<%= f.label :name %>
				<%= f.text_field :name %>
			</li>
			<li>
				<%= f.label :bio %>
				<%= f.text_field :bio %>
			</li>
		</ol>
	</fieldset>
	<fieldset>
		<%= submit_tag "Submit", :id => "submit-btn" %>
	</fieldset>
<% end %>

app/views/artists/show.html.erb
<div class="artist">
	<h1><%= @artist.name %></h1>
	<p><%= @artist.bio %></p>
	<p><%= link_to	'Edit', edit_artist_path(@artist) %></p>
</div>

<hr>

<h2>Releases</h2>

<%- if @artist.releases.empty? -%>
	<p>This artist has no releases.</p>
<%- else -%>
	<%= render :partial => "releases/release", :collection => @artist.releases, :locals => {:release_class => "artistsreleases"} %>
<%- end -%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Recordlabel</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
	<%= yield %>
</div>

</body>
</html>

app/views/layouts/releases.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @title || "Releases" %></title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= javascript_include_tag "releases" %>
  <%= csrf_meta_tag %>
</head>
<body>

<div id="container">
	<%= yield %>
</div>

</body>
</html>

app/views/releases/_no_releases.html.haml
.release
	%p= "There are no releases"
	%p
		Would you like to
		- one_line do
			= link_to 'add a release', new_release_path
			?

app/views/releases/_release.html.haml
.release{:id => "release#{release.id}"}
	%h3
		= link_to release.artist.name, artist_path(release.artist)
		&= "-"
		= link_to release.title, release_path(release)
		
	%p= raw release.description
	%p
		- unless release.duration.blank?
			Duration: #{release.duration}
			%br
		- unless release.catalogue_number.blank?
			Catalogue Number: #{release.catalogue_number}
	%p
		= link_to "Edit", edit_release_path(release), :id => "edit" << release.id.to_s
		&= "|"
		= link_to_destroy "Delete", release_path(release), confirm_destroy_release_path(release), form_authenticity_token, "delete" << release.id.to_s

				

app/views/releases/_release_form.html.erb
<%= form_for @release do |f| %>
<fieldset>
	<ol>
		<li>
			<%= f.label :artist_name, "Artist" %>
			<%= f.text_field :artist_name %>
		</li>
		<li>
			<%= f.label :title %>
			<%= f.text_field :title %>
		</li>
		<li>
			<%= f.label :description %>
			<%= f.text_area :description %>
		</li>
		<li>
			<%= f.label :duration %>
			<%= f.text_field :duration %>
		</li>
		<li>
			<%= f.label :catalogue_number, "Catalogue Number" %>
			<%= f.text_field :catalogue_number %>
		</li>
	</ol>
</fieldset>
<fieldset>
	<%= submit_tag "Submit", :id =>"submit-btn" %>
</fieldset>
<% end %>

app/views/releases/confirm_destroy.html.erb
<%= form_for :release, :url => release_path(@release), :html => {:method => :delete} do |f| %>
	<h2>Are you sure you want to delete this release?</h2>
	<p>
		<%= submit_tag "Delete" %>
		or 
		<%= link_to "Cancel", releases_path %>
	</p>
<% end %>

app/views/releases/edit.html.erb
<%= render "release_form" %>

app/views/releases/index.html.erb
<%- flash.each do |name, msg| -%>
	<%= content_tag :div, msg, :id => "flash_#{name}", :class => "notice" %>
<%- end -%>

<%- if @releases.empty? -%>
	<%= render "no_releases" %>
<%- else -%>
	<%= render @releases %>
<%- end -%>

app/views/releases/new.html.erb
<%= render "release_form" %>

app/views/releases/show.html.erb
<div class="release">
	<h1><%= @release.title %></h1>
	<p><%= @release.description %></p>
</div>